### ISSUE TITLE
No qualifying bean of type [org.dukecon.server.adapter.ConferenceDataProvider] found

### ISSUE THREAD

**Issue by ascheman** [jugda/dukecon_server#47]
Automatic testing fails with error `No qualifying bean of type [org.dukecon.server.adapter.ConferenceDataProvider] found`, cf. https://dev.dukecon.org/jenkins/view/Build%20Pipeline%20Develop/job/dukecon_server_develop/lastBuild/org.dukecon$dukecon-server-springboot/testReport/org.dukecon.server.favorite/FavoritesRepositorySpec/test_simple_insert/

**Comment by ascheman** [comment]
Seems this is broken since the dynamic conference configuration was introduced?
I have disabled test cases for now (ignore). @sippsack could you please check what the real problem was and how we could resolve this? Looks like there was no instance of ConferenceDataProvider was introduced during tests?

**Comment by sippsack** [comment]
dynamic conference configuration will be loaded through spring context initializer which had to be used in the integration tests as well

https://github.com/dukecon/dukecon_server/commit/151a7f129445364465a68c8e66040357ca5d0ad8
