### ISSUE TITLE
Conference Data: please provide Link to Conference Home page

### ISSUE THREAD

**Issue by steffchep** [jugda/dukecon_server#49]
The conference Data currently only returns the URL where the planner is reachable.
We also need the link to the Homepage (suggestion: "homePageUrl"). 

We can use the currently provided name as text for the link, but this seems to grow quite long in some cases ("DOAG Konferenz + Ausstellung 2016"). Suggestions?

**Comment by sippsack** [comment]
fixed in 14c01d3ef877bcca6530b0916cba7f8c961cce4d

e. g. "homeUrl":"http://www.javaland.eu"

my opinion to conference name:
* content is free configurable, so it may be shortened in agreement with DOAG office
* or we could cut it after 10 chars in JavaScript
* or we need a new json field shortName
