### ISSUE TITLE
DukeCon JL 2017 is missing a talk

### ISSUE THREAD

**Issue by ascheman** [jugda/dukecon_server#52]
In the old Javaland conference planer we can see the talk of @chkal and @ivargrimstad: https://www.javaland.eu/konferenz/konferenzplaner/konferenzplaner_details.php?id=522447&locS=0&vid=529457.

However, DukeCon does not contain the talk. It is missing from the JSON we send to the frontend: https://dev.dukecon.org/latest/rest/conferences/jl2017

**Comment by steffchep** [comment]
https://dev.dukecon.org/latest/?search=grimstad
https://dev.dukecon.org/latest/?search=kalte
... looks like the are there?

**Comment by sippsack** [comment]
we filter for invalid begin and end timestamps, this talk starts at 15 p.m. and ends at 14:50 p.m.

I'll create an issue in redmine

**Comment by sippsack** [comment]
https://redmine.doag.org/issues/4175
