### ISSUE TITLE
Filter out/convert special characters from DOAG data import

### ISSUE THREAD

**Issue by ascheman** [jugda/dukecon_server#53]
At least from the DOAG data imports we get strange characters (e.g., \222) which cannot be displayed correctly. We need to sort them out or convert them (it seems to be mostly ', `, ´or --longdash).

Probably it's a question of character sets for export/import?

![screenshot_20170318-072445](https://cloud.githubusercontent.com/assets/456000/24070402/fecba3cc-0bbc-11e7-9c4a-6bf5c5986a26.png)

![clipboard02](https://cloud.githubusercontent.com/assets/456000/24070403/04c05002-0bbd-11e7-8ca1-94a224dbb8ca.jpg)

![clipboard01](https://cloud.githubusercontent.com/assets/456000/24070404/0927120c-0bbd-11e7-885c-0c7c7c493a33.jpg)

**Comment by pittorf** [comment]
corrected in the next JSON export
